language: php
php:
  #- '5.5'
  - '5.6'

services:
  - mysql

env:
  #- CI_ENV=development
  - CI_ENV=testing
  #- CI_ENV=production

before_script:
  - composer update
  - chmod 0777 ./bin/test.sh

script: ./bin/test.sh

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always

#after_success:
 # - ./bin/deploy.sh